web:
  image: ddaze/invenio-dev
  # build: .
  command: serve
  environment:
    - PORT=4000
    - EMAIL='invenio@example.de'
    # HOST: Hostname or IP address Invenio is listening
    - HOST=127.0.0.1
    - CACHE_REDIS_HOST=cache
    - CFG_DATABASE_HOST=db
    - INVENIO_APP_CONFIG_ENVS=CACHE_REDIS_HOST,CFG_DATABASE_HOST
  links:
    - mysql:db
    - redis:redis
  volumes_from:
    - data
#  volumes:
#    - .:/src/invenio
  ports:
      - "127.0.0.1:4000:4000"
redis:
  image: redis
  ports:
      - "127.0.0.1:6379:6379"
mysql:
  image: ddaze/mysql
  volumes_from:
    - data
  environment:
    - MYSQL_DATABASE=invenio
    - MYSQL_USER=invenio
    - MYSQL_PASSWORD=my123p
    - MYSQL_ROOT_PASSWORD=mysecretpassword
data:
  image: ddaze/invenio-legacy-data
#  command: mkdir -p /src/invenio && /bin/true
#  volumes:
#    - /var/lib/mysql
#    - /opt/invenio
#    - /src

